---
 req_packages:
   - linter-docker
   - platformio-ide-terminal
# - change-tabs
# - expose
# - linter-crystal
# - split-diff
# - tidy-tabs
# - advanced-open-file
# - color-picker
# - file-icons
# - merge-conflicts
# - stash-tabs
# - todo-show
# - aligner
# - color-tabs
# - git-blame
# - minimap
# - swackets
# - tool-bar
# - ask-stack
# - crystal-block
# - git-plus
# - open-recent
# - symbols-tree-view
# - tool-bar-almighty
# - atom-commander
# - crystal-tools
# - highlight-line
# - pinned-tabs
# - sync-settings
# - vim-mode
# - atom-ctags
# - custom-invisibles
# - highlight-selected
# - project-manager
# - tab-numbers
# - atom-ungit
# - docblockr
# - language-crystal-actual
# - redui-jm-syntax
# - tab-switcher
# - autocomplete-ctags
# - ex-mode
# - linter
# - regex-railroad-diagram
