---
- name: Install apps with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - "0xed"
    - atom
    - blender
    - clocker
    - gimp
    - google-chrome
    - jetbrains-toolbox
    - kindle
    - krita
    - macdown
    - mpv
    - obs
    - processing
    - spectacle
    - steam
    - virtualbox
    - visual-studio-code
