---
- name: Install utils with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - clocker
    - disk-inventory-x
    - flycut
    - font-source-code-pro
    - google-backup-and-sync
    - iterm2
    - minikube
    - minishift
    - quicklook-csv
    - quicklook-json
    - spectacle
    - ttscoff-mmd-quicklook
    - xquartz
