---
- name: Install utils with homebrew-cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - clocker
    - disk-inventory-x
    - docker
    - flycut
    - google-backup-and-sync
    - gpg-suite
    - iterm2
    - minikube
    - minishift
    - spectacle
    - ttscoff-mmd-quicklook
    - xquartz
